export default {
  login: "akibhasan50",
  id: 40955867,
  node_id: "MDQ6VXNlcjQwOTU1ODY3",
  avatar_url: "https://avatars.githubusercontent.com/u/40955867?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/akibhasan50",
  html_url: "https://github.com/akibhasan50",
  followers_url: "https://api.github.com/users/akibhasan50/followers",
  following_url:
    "https://api.github.com/users/akibhasan50/following{/other_user}",
  gists_url: "https://api.github.com/users/akibhasan50/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/akibhasan50/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/akibhasan50/subscriptions",
  organizations_url: "https://api.github.com/users/akibhasan50/orgs",
  repos_url: "https://api.github.com/users/akibhasan50/repos",
  events_url: "https://api.github.com/users/akibhasan50/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/akibhasan50/received_events",
  type: "User",
  site_admin: false,
  name: "Akib Hasan",
  company: "Golden Harvest Infotech",
  blog: "akibhasan.info",
  location: "Dhaka,Bangladesh",
  email: null,
  hireable: null,
  bio: "Declare Variable, not War.",
  twitter_username: "tonuakibhasan",
  public_repos: 59,
  public_gists: 0,
  followers: 4,
  following: 10,
  created_at: "2018-07-08T15:02:01Z",
  updated_at: "2022-03-23T17:46:55Z",
};
